#!/usr/bin/with-contenv bash

mkdir -p /config/{extensions,data,workspace,.ssh}

if [ -n "${SUDO_PASSWORD}" ] || [ -n "${SUDO_PASSWORD_HASH}" ]; then
  echo "setting up sudo access"
  if ! grep -q 'appuser' /etc/sudoers; then
    echo "adding appuser to sudoers"
    echo "appuser ALL=(ALL:ALL) ALL" >> /etc/sudoers
  fi
  if [ -n "${SUDO_PASSWORD_HASH}" ]; then
    echo "setting sudo password using sudo password hash"
    sed -i "s|^appuser:\!:|appuser:${SUDO_PASSWORD_HASH}:|" /etc/shadow
  else
    echo "setting sudo password using SUDO_PASSWORD env var"
    echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd appuser
  fi
fi

# permissions
chown -R appuser:appuser \
	/config
